# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20161120_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='business',
            new_name='business_name',
        ),
    ]
